# Generated by Django 4.1.5 on 2023-01-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('buy_in', models.PositiveIntegerField()),
                ('players', models.ManyToManyField(to='leaderboard.player')),
            ],
        ),
    ]
