# Generated by Django 4.1.5 on 2023-01-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_alter_game_buy_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
    ]
