# Generated by Django 4.1.5 on 2023-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('peak_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
