# Generated by Django 4.1.5 on 2023-01-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_buyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
