# Generated by Django 4.1.5 on 2023-01-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_alter_game_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
