# Generated by Django 4.1.5 on 2023-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_game_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buy_in',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
